package com.ibm.aimonitoring.processor.config;

import co.elastic.clients.elasticsearch.ElasticsearchClient;
import co.elastic.clients.json.jackson.JacksonJsonpMapper;
import co.elastic.clients.transport.rest_client.RestClientTransport;
import org.apache.http.HttpHost;
import org.apache.http.auth.AuthScope;
import org.apache.http.auth.UsernamePasswordCredentials;
import org.apache.http.client.config.RequestConfig;
import org.apache.http.conn.ssl.NoopHostnameVerifier;
import org.apache.http.impl.client.BasicCredentialsProvider;
import org.apache.http.impl.nio.client.HttpAsyncClientBuilder;
import org.apache.http.impl.nio.reactor.IOReactorConfig;
import org.apache.http.ssl.SSLContexts;
import org.elasticsearch.client.RestClient;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import javax.net.ssl.HttpsURLConnection;
import javax.net.ssl.SSLContext;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.GeneralSecurityException;
import java.security.KeyStore;
import java.security.cert.Certificate;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * Elasticsearch configuration. Tunes the low-level HTTP client (Apache HttpClient 4.x
 * used by Elasticsearch {@code RestClient}): TCP keep-alive and request timeouts help
 * when load balancers or Elasticsearch close idle connections.
 * <p>
 * {@code elasticsearch.scheme} must match the server (HTTP vs HTTPS); TLS endpoints will
 * close plaintext connections, which surfaces as {@code ConnectionClosedException} on the client.
 * <p>
 * For HTTPS with a private or auto-generated CA (e.g. Bitnami {@code tls.autoGenerated}),
 * configure {@code elasticsearch.ssl.ca-bundle-path} or, only for non-production,
 * {@code elasticsearch.ssl.insecure} to avoid PKIX errors.
 * <p>
 * When Elasticsearch has security enabled (e.g. Bitnami {@code security.enabled}),
 * set {@code elasticsearch.username} and {@code elasticsearch.password} for HTTP Basic auth.
 */
@Configuration
public class ElasticsearchConfig {

    private static final Logger log = LoggerFactory.getLogger(ElasticsearchConfig.class);

    @Bean(destroyMethod = "close")
    public RestClient restClient(
            @Value("${elasticsearch.host:localhost}") String host,
            @Value("${elasticsearch.port:9200}") int port,
            @Value("${elasticsearch.scheme:http}") String scheme,
            @Value("${elasticsearch.connect-timeout-ms:10000}") int connectTimeoutMs,
            @Value("${elasticsearch.socket-timeout-ms:120000}") int socketTimeoutMs,
            @Value("${elasticsearch.ssl.ca-bundle-path:}") String sslCaBundlePath,
            @Value("${elasticsearch.ssl.insecure:false}") boolean sslInsecure,
            @Value("${elasticsearch.username:}") String username,
            @Value("${elasticsearch.password:}") String password) throws GeneralSecurityException, IOException {

        String normalizedScheme = scheme == null ? "http" : scheme.trim().toLowerCase();
        if (!"http".equals(normalizedScheme) && !"https".equals(normalizedScheme)) {
            throw new IllegalArgumentException(
                    "elasticsearch.scheme must be 'http' or 'https', got: " + scheme);
        }

        final TlsClientSettings tls = "https".equals(normalizedScheme)
                ? buildTlsClientSettings(sslCaBundlePath, sslInsecure)
                : null;
        final boolean useBasicAuth = username != null && !username.isBlank();

        return RestClient.builder(new HttpHost(host, port, normalizedScheme))
                .setHttpClientConfigCallback((HttpAsyncClientBuilder builder) -> {
                    builder.setDefaultIOReactorConfig(
                            IOReactorConfig.custom()
                                    .setSoKeepAlive(true)
                                    .build());
                    builder.setDefaultRequestConfig(
                            RequestConfig.custom()
                                    .setConnectTimeout(connectTimeoutMs)
                                    .setSocketTimeout(socketTimeoutMs)
                                    .build());
                    if (tls != null) {
                        builder.setSSLContext(tls.sslContext());
                        builder.setSSLHostnameVerifier(tls.hostnameVerifier());
                    }
                    if (useBasicAuth) {
                        BasicCredentialsProvider credentialsProvider = new BasicCredentialsProvider();
                        credentialsProvider.setCredentials(
                                AuthScope.ANY,
                                new UsernamePasswordCredentials(
                                        username.trim(),
                                        password != null ? password : ""));
                        builder.setDefaultCredentialsProvider(credentialsProvider);
                    }
                    return builder;
                })
                .build();
    }

    private TlsClientSettings buildTlsClientSettings(String sslCaBundlePath, boolean sslInsecure)
            throws GeneralSecurityException, IOException {

        String path = sslCaBundlePath == null ? "" : sslCaBundlePath.trim();
        if (sslInsecure) {
            log.warn(
                    "Elasticsearch TLS verification is disabled (elasticsearch.ssl.insecure=true); "
                            + "use only for development or with a locked-down network.");
            SSLContext ctx = SSLContexts.custom()
                    .loadTrustMaterial(null, (chain, authType) -> true)
                    .build();
            return new TlsClientSettings(ctx, NoopHostnameVerifier.INSTANCE);
        }
        if (!path.isEmpty()) {
            SSLContext ctx = sslContextTrustingPemCaBundle(Paths.get(path));
            return new TlsClientSettings(ctx, HttpsURLConnection.getDefaultHostnameVerifier());
        }
        log.warn(
                "Elasticsearch HTTPS is enabled but no CA bundle is configured and insecure mode is off; "
                        + "set elasticsearch.ssl.ca-bundle-path or ELASTICSEARCH_SSL_CA_BUNDLE_PATH "
                        + "(or elasticsearch.ssl.insecure for dev only) to avoid PKIX errors.");
        return null;
    }

    private record TlsClientSettings(SSLContext sslContext, javax.net.ssl.HostnameVerifier hostnameVerifier) {
    }

    private static SSLContext sslContextTrustingPemCaBundle(Path pemPath)
            throws GeneralSecurityException, IOException {
        if (!Files.isRegularFile(pemPath)) {
            throw new IOException("Elasticsearch CA bundle path is not a file: " + pemPath);
        }
        CertificateFactory cf = CertificateFactory.getInstance("X.509");
        List<X509Certificate> certs = new ArrayList<>();
        try (InputStream is = Files.newInputStream(pemPath)) {
            Collection<? extends Certificate> generated = cf.generateCertificates(is);
            for (Certificate c : generated) {
                certs.add((X509Certificate) c);
            }
        }
        if (certs.isEmpty()) {
            throw new IOException("No X.509 certificates found in: " + pemPath);
        }
        KeyStore ks = KeyStore.getInstance(KeyStore.getDefaultType());
        ks.load(null, null);
        for (int i = 0; i < certs.size(); i++) {
            ks.setCertificateEntry("es-ca-" + i, certs.get(i));
        }
        javax.net.ssl.TrustManagerFactory tmf = javax.net.ssl.TrustManagerFactory.getInstance(
                javax.net.ssl.TrustManagerFactory.getDefaultAlgorithm());
        tmf.init(ks);
        SSLContext ctx = SSLContext.getInstance("TLS");
        ctx.init(null, tmf.getTrustManagers(), null);
        return ctx;
    }

    @Bean
    public ElasticsearchClient elasticsearchClient(RestClient restClient) {
        RestClientTransport transport = new RestClientTransport(
                restClient,
                new JacksonJsonpMapper()
        );
        return new ElasticsearchClient(transport);
    }
}
